default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  adapter: postgresql
  database: <%= ENV['TEMPLATEAPP_DATABASE'] %>
  username: <%= ENV['TEMPLATEAPP_DATABASE_USER'] %>
  password: <%= ENV['TEMPLATEAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['TEMPLATE_DATABASE_HOSTNAME'] %>
  port: 5432

test:
  <<: *default
  adapter: postgresql
  database: <%= ENV['TEMPLATEAPP_DATABASE'] %>
  username: <%= ENV['TEMPLATEAPP_DATABASE_USER'] %>
  password: <%= ENV['TEMPLATEAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['TEMPLATE_DATABASE_HOSTNAME'] %>
  port: 5432

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['TEMPLATEAPP_DATABASE'] %>
  username: <%= ENV['TEMPLATEAPP_DATABASE_USER'] %>
  password: <%= ENV['TEMPLATEAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['TEMPLATE_DATABASE_HOSTNAME'] %>
  port: 5432

