default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

